/**
 * VideoStoryboard schema -- matches the Pydantic models in Agno/nexus.py.
 *
 * The Scriptwriter agent saves this JSON to public/content/<slug>.json.
 * Remotion reads it to render the video; the generate pipeline reads it
 * to produce images, voiceover, music, and captions.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Zod schemas (runtime validation)
// ---------------------------------------------------------------------------

export const VideoSceneSchema = z.object({
  /** Narration text for this scene (Spanish). */
  text: z.string(),
  /** Detailed image/visual description for AI image generation. */
  visual: z.string(),
  /** Scene duration in seconds (2-15). */
  duration_seconds: z.number().int().min(2).max(15),
  /** Transition type: fade, slide, cut, zoom. */
  transition: z.enum(["fade", "slide", "cut", "zoom"]).default("fade"),
});

export const VideoStyleSchema = z.object({
  font: z.string().default("Inter"),
  primary_color: z.string().default("#1a1a2e"),
  accent_color: z.string().default("#e94560"),
});

export const VideoStoryboardSchema = z.object({
  /** Video title. */
  title: z.string(),
  /** Selected hook (first 3 seconds). */
  hook: z.string(),
  /** Content language (default: "es"). */
  language: z.string().default("es"),
  /** Total video duration in seconds. */
  total_duration_seconds: z.number().int().positive(),
  /** Ordered list of scenes. */
  scenes: z.array(VideoSceneSchema).min(1),
  /** Platform hashtags. */
  hashtags: z.array(z.string()),
  /** Call to action at the end. */
  cta: z.string(),
  /** Target platform. */
  platform: z
    .enum(["instagram_reels", "tiktok"])
    .default("instagram_reels"),
  /** Visual style configuration. */
  style: VideoStyleSchema.default({
    font: "Inter",
    primary_color: "#1a1a2e",
    accent_color: "#e94560",
  }),
});

// ---------------------------------------------------------------------------
// TypeScript types (inferred from Zod)
// ---------------------------------------------------------------------------

export type VideoScene = z.infer<typeof VideoSceneSchema>;
export type VideoStyle = z.infer<typeof VideoStyleSchema>;
export type VideoStoryboard = z.infer<typeof VideoStoryboardSchema>;

// ---------------------------------------------------------------------------
// Asset manifest -- generated by the pipeline, consumed by Remotion
// ---------------------------------------------------------------------------

/** Word-level timestamp for caption rendering. */
export interface WordTimestamp {
  word: string;
  /** Start time in seconds. */
  start: number;
  /** End time in seconds. */
  end: number;
}

/** Per-scene generated assets. */
export interface SceneAssets {
  /** Index of the scene in the storyboard. */
  index: number;
  /** Path to the generated image (relative to public/). */
  imagePath: string;
  /** Path to the voiceover audio (relative to public/). */
  audioPath: string;
  /** Voiceover duration in milliseconds. */
  audioDurationMs: number;
  /** Word-level timestamps for caption sync. */
  words: WordTimestamp[];
}

/** Complete asset manifest for a video. */
export interface AssetManifest {
  /** Slug identifier for this video. */
  slug: string;
  /** Reference to the source storyboard. */
  storyboard: VideoStoryboard;
  /** Per-scene assets. */
  scenes: SceneAssets[];
  /** Path to background music (relative to public/). */
  musicPath: string;
  /** Music duration in milliseconds. */
  musicDurationMs: number;
  /** Total video duration in frames (fps * seconds). */
  totalFrames: number;
}
